[tool.poetry]
name = "awel-tutorial"
version = "0.1.0"
description = ""
authors = ["Qfymz <yuelaojun@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
dbgpt = "^0.6.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
